name: CI
on: 
  push:
    branches: [ master ]
    
  workflow_dispatch:
jobs:
  cache_checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: my-checkout-${{ github.run_id }}
          path: ${{ github.workspace }}/**/*
          
  run_superlinter:
    needs: cache_checkout
    uses: ./.github/workflows/superlinter.yaml
    
  run_tests:
    needs: cache_checkout
    uses: ./.github/workflows/tests.yaml
