name: Super-linter

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Get Cached Checkout
        uses: actions/download-artifact@v3
        with:
          name: my-checkout-${{ github.run_id }}

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_STANDARD: false

